export const CountryData = [
    {
        Country:"Afghanistan",
        Capital:"Kabul",
        Currency:"Afghani",
        Language:"Pashto, Dari (Persian)",
        Religion:"Islam",
    },
    {
        Country:"Albania",
        Capital:"Tirana",
        Currency:"Lek",
        Language:"Albanian",
        Religion:"Islam, Christianity",
    },
    {
        Country:"Algeria",
        Capital:"Algiers",
        Currency:"Algerian Dinar",
        Language:"Arabic; Tamazight; French",
        Religion:"Islam",
    },
    {
        Country:"Andorra",
        Capital:"Andorra la Vella",
        Currency:"Euro",
        Language:"Catalan",
        Religion:"Christianity",
    },
    {
        Country:"Angola",
        Capital:"Luanda",
        Currency:"Kwanza",
        Language:"Portuguese",
        Religion:"Christianity",
    },
    {
        Country:"Antigua & Barbuda",
        Capital:"Saint John's",
        Currency:"East Caribbean Dollar",
        Language:"English",
        Religion:"Christianity",
   },
   {
    Country:"Argentina",
    Capital:"Buenos Aires",
    Currency:"Argentine Peso",
    Language:"Spanish",
    Religion:"Christianity (But Secular Country)",
   },
   {
    Country:"Armenia",
    Capital:"Yerevan",
    Currency:"Dram",
    Language:"Armenian",
    Religion:"Christianity",
   },
   {
    Country:"Australia",
    Capital:"Canberra",
    Currency:"Australian Dollar",
    Language:"English",
    Religion:"Christianity (But Secular Country)",
   },
   {
    Country:"Austria",
    Capital:"Vienna",
    Currency:"Euro",
    Language:"German",
    Religion:"Christianity",
   },
   {
    Country:"Azerbaijan",
    Capital:"Baku",
    Currency:"Manat",
    Language:"Azerbaijani",
    Religion:"Islam",
   },
   {
    Country:"The Bahamas",
    Capital:"Nassau",
    Currency:"Bahamian Dollar",
    Language:"English",
    Religion:"Christianity",
   },
   {
    Country:"Bahrain",
    Capital:"Manama",
    Currency:"Bahraini Dinar",
    Language:"Arabic",
    Religion:"Islam",
   },
   {
    Country:"Bangladesh",
    Capital:"Dhaka",
    Currency:"Taka",
    Language:"Bangla",
    Religion:"Islam",
   },
   {
    Country:"Barbados",
    Capital:"Bridgetown",
    Currency:"Barbadian Dollar",
    Language:"English",
    Religion:"Christianity",
   },
   {
    Country:"Belarus",
    Capital:"Minsk",
    Currency:"Belarusian Ruble",
    Language:"Belarusian; Russian",
    Religion:"Christianity",
   },
   {
    Country:"Belgium",
    Capital:"Brussels",
    Currency:"Euro",
    Language:"Dutch; French; German",
    Religion:"Secular",
   },
   {
    Country:"Belize",
    Capital:"Belmopan",
    Currency:"Belize Dollar",
    Language:"English",
    Religion:"Christianity",
   },
   {
    Country:"Benin",
    Capital:"Porto-Novo",
    Currency:"West African CFA Franc",
    Language:"French",
    Religion:"Christianity",
   },
   {
    Country:"Bhutan",
    Capital:"Thimphu",
    Currency:"Ngultrum",
    Language:"Dzongkha",
    Religion:"Buddhism, Hindu",
   },
   {
    Country:"Bosnia & Herzegovina",
    Capital:"Sarajevo",
    Currency:"Convertible Mark",
    Language:"Bosnian; Croatian; Serbian",
    Religion:"Islam, Christianity",
   },
   {
    Country:"Botswana",
    Capital:"Gaborone",
    Currency:"Pula",
    Language:"English; Tswana	",
    Religion:"Christianity",
   },
   {
    Country:"Brazil",
    Capital:"Brasilia",
    Currency:"Real",
    Language:"Portuguese",
    Religion:"Christianity",
   },
   {
    Country:"Brunei",
    Capital:"Bandar Seri Begawan",
    Currency:"Brunei Dollar	",
    Language:"Malay",
    Religion:"Islam",
   },
   {
    Country:"Bulgaria",
    Capital:"Sofia",
    Currency:"Lev",
    Language:"Bulgarian",
    Religion:"Secular",
   },
]